Repository DOOMSTERR/HACKTOBER_22, pull requests merged in 2022-10, with the labels that each got.

#4 Create Bubble_sort.java
  Bubble_sort.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#3 Create Palindrome.java
  Palindrome.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#1 Create BerlinClock.py
  python/BerlinClock.py
Labels: hacktoberfest, hacktoberfest-accepted

#2 Create insertion_sort.c
  insertion_sort.c
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#6 added a python script for body detection in an image.
  Body_detector/bdect.py
  Body_detector/haarcascade_fullbody.xml
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#5 Create sudoku.cpp
  c++/sudoku.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#9 Create element.java
  element.java
Labels: hacktoberfest, hacktoberfest-accepted

#8 Create BST_search.java
  Java/BST_search.java
Labels: hacktoberfest, hacktoberfest-accepted

#7 Create trapping_rainwater.cpp
  c++/trapping_rainwater.cpp
Labels: hacktoberfest, hacktoberfest-accepted
